// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aivmjrudkwhirydzfahe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpdm1qcnVka3doaXJ5ZHpmYWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjI3MzMsImV4cCI6MjA2NTAzODczM30.ErbVPTXlsc3DVZzBsy3te29YIt8XRJlKz9FcsZtrMTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);